### ISSUE TITLE
table-key-properties does not work (use key-properties instead)

### ISSUE THREAD

**Issue by steven-luabase** [MeltanoLabs/tap-bigquery#51]
Same issue described here in `tap-postgres`:
https://github.com/meltano/sdk/issues/2660#issuecomment-2484236920

Doesn't work:
```
plugins:
  extractors:
  - name: tap-bigquery
    variant: meltanolabs
    metadata:
      '*-events_*':
        table-key-properties:
        - _id
```

Does work:
```
plugins:
  extractors:
  - name: tap-bigquery
    variant: meltanolabs
    metadata:
      '*-events_*':
        key-properties:
        - _id
```
